"""empty message

Revision ID: 4e9c8cd4c53b
Revises: 38da9da9a4fd
Create Date: 2025-01-24 12:54:59.167535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9c8cd4c53b'
down_revision: Union[str, None] = '38da9da9a4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'label')
    # ### end Alembic commands ###
