"""empty message

Revision ID: a141c6aeced8
Revises: 4e9c8cd4c53b
Create Date: 2025-01-24 14:50:58.862413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a141c6aeced8'
down_revision: Union[str, None] = '4e9c8cd4c53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'next_column')
    op.drop_column('items', 'one')
    op.drop_column('items', 'new_column')
    op.drop_column('items', 'new')
    op.drop_column('items', 'hello')
    op.drop_column('items', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('hello', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('new', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('new_column', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('one', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('next_column', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
